<<<<<<< HEAD
<<<<<<< HEAD
ignoredBuiltDependencies:
=======
onlyBuiltDependencies:
>>>>>>> refs/remotes/origin/main
=======
onlyBuiltDependencies:
>>>>>>> 6b1f6d74b51cf09f37162d593ed52e813b60c4f5
  - esbuild
  - sharp
  - unrs-resolver
