import "~/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";
import { TopNav } from "./_components/topnav";
import { Footer } from "./_components/footer";
import { ClerkProvider } from "@clerk/nextjs";
import { CartProvider } from "../context/CartContext";

export const metadata: Metadata = {
  title: "Lcarpio's Flower Shop",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geist.variable}`}>
      <body>
        <div id="app">
          <ClerkProvider>
            <CartProvider>
              <TopNav />
              {children}
              <Footer />
            </CartProvider>
          </ClerkProvider>
        </div>
      </body>
    </html>
  );
}
